startproject:
	docker-compose run web django-admin.py startproject example .

build:
	docker-compose build

up:
	docker-compose -p django up -d

down:
	docker-compose -p django down

ps:
	docker ps -a|grep django
